USE [master]
GO

/****** Object:  Database [dbHarryPotter]    Script Date: 14/08/2020 11:26:08 ******/
CREATE DATABASE [dbHarryPotter]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbHarryPotter', FILENAME = N'/var/opt/mssql/data/dbHarryPotter.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbHarryPotter_log', FILENAME = N'/var/opt/mssql/data/dbHarryPotter_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [dbHarryPotter] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbHarryPotter].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbHarryPotter] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbHarryPotter] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbHarryPotter] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbHarryPotter] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbHarryPotter] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbHarryPotter] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbHarryPotter] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbHarryPotter] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbHarryPotter] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbHarryPotter] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbHarryPotter] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbHarryPotter] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbHarryPotter] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbHarryPotter] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbHarryPotter] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbHarryPotter] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbHarryPotter] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbHarryPotter] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbHarryPotter] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbHarryPotter] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbHarryPotter] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbHarryPotter] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbHarryPotter] SET RECOVERY FULL 
GO

ALTER DATABASE [dbHarryPotter] SET  MULTI_USER 
GO

ALTER DATABASE [dbHarryPotter] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbHarryPotter] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbHarryPotter] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbHarryPotter] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dbHarryPotter] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbHarryPotter] SET QUERY_STORE = OFF
GO

ALTER DATABASE [dbHarryPotter] SET  READ_WRITE 
GO


